version: '3.2'
services:
  elisma:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        SERVER_PORT: 3000
    command: sh -c "/wait && cd /app && npx ts-node-dev -r tsconfig-paths/register --inspect=0.0.0.0:1339 -P ./tsconfig.json src/"
    environment:
      - NODE_ENV=development
      - SERVER_HOST
      - SERVER_PORT
      - SERVER_PUBLIC_DIR
      - OPEN_AI_API_KEY
    ports:
      - '9000:3000'
      - '6122:1339'
    volumes:
      - ./:/app
      - ./.env:/app/.env
