export enum LibCategory {
  WebFramework = 'web framework',
  Logger = 'logger',
  DatabaseDriver = 'database driver',
  ORM = 'orm',
  ActiveRecord = 'active record',
  DataStore = 'data store',
  Queue = 'queue',
  Infra = 'infrastructure',
  Configuration = 'configuration',
  Documentation = 'documentation',
  CLI = 'command line interface',
  Loader = 'loader',
  Other = 'other',
}
